### ISSUE TITLE
Error when starting AYA

### ISSUE THREAD

**Issue by Revilum** [Jigoku/blackweb_aya#6]
`$ ./ayatool_qt.py
Traceback (most recent call last):
  File "./ayatool_qt.py", line 183, in <module>
    main()
  File "./ayatool_qt.py", line 177, in main
    form = AyaTool()
  File "./ayatool_qt.py", line 57, in __init__
    blackweb_aya.open_usb()
  File "/home/nils/Downloads/ayatool-master/blackweb_aya.py", line 37, in open_usb
    raise ValueError("Device is not connected")
ValueError: Device is not connected
`

any idea how to solve it?

**Comment by Jigoku** [comment]
Hi, sorry i didn't noticed an issue was opened until just now. 

What is the output of `lsusb` on your computer?

Do you see something like:
```
Bus 008 Device 002: ID 3938:1101  

```

The `3938:1101` is the important bit.
